src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PhotoRepository::class)]
class Photo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToMany(targetEntity: Produit::class, mappedBy: 'Photo')]
    private Collection $produits;

    #[ORM\ManyToOne(inversedBy: 'photos')]
    private ?Produit $produit = null;

    #[ORM\Column(length: 100)]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $chemin = null;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): static
    {
        $this->produit = $produit;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getChemin(): ?string
    {
        return $this->chemin;
    }

    public function setChemin(string $chemin): static
    {
        $this->chemin = $chemin;

        return $this;
    }

}

src/Entity/Supporter.php
<?php

namespace App\Entity;

use App\Repository\SupporterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SupporterRepository::class)]
class Supporter
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\ManyToOne(inversedBy: 'supporters')]
    private ?Produit $produit = null;

    #[ORM\ManyToOne(inversedBy: 'supporters')]
    private ?Support $Support = null;

    

    public function __construct()
    {
        $this->supports = new ArrayCollection();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): static
    {
        $this->produit = $produit;

        return $this;
    }

    public function getSupport(): ?Support
    {
        return $this->Support;
    }

    public function setSupport(?Support $Support): static
    {
        $this->Support = $Support;

        return $this;
    }

    
}

src/Controller/ListeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Produit;
use App\Repository\ProduitRepository;
class ListeController extends AbstractController
{
    #[Route('/private-adorer/{id}', name: 'app_adorer')]
    public function adorer(Produit $Produit,EntityManagerInterface $em, ): Response
    {
        if ($this->getUser()->getAimer()->contains($Produit)) {
            $this->getUser()->removeAimer($Produit);
        } else {
            $this->getUser()->addAimer($Produit);
        }
        $em->persist($this->getUser());
        $em->flush();
        return $this->redirectToRoute('app_base');
    }

    #[Route('/Private-Liste_favoris', name:'app_liste_favoris')]
    public function favoris() : Response
    {
        $favoris=$this->getUser()->getAimer();
        return $this->render('liste/liste-favoris.html.twig', [
            'Favoris'=> $favoris,
        ]);
        
    }

    #[Route('/private-adorer-liste/', name: 'app_adorer_liste')]
    public function adorerListe(Produit $Produit,EntityManagerInterface $em, ): Response
    {
        if ($this->getUser()->getAimer()->contains($Produit)) {
            $this->getUser()->removeAimer($Produit);
        } else {
            $this->getUser()->addAimer($Produit);
        }
        $em->persist($this->getUser());
        $em->flush();
        return $this->redirectToRoute('app_Produit');
    }
}

templates/liste/liste-favoris.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}-Favoris
{% endblock %}
{% block body %}
	<h1 class="text-center text-primary mt-4 pt-4 display-1 fw-bold">Vos Favoris</h1>
	{% for Favori in Favoris %}
		<div class="card-group">
			{% for Produit in Favori.aimer %}
				<div class="col">
					<div class="card" style="width: 16rem;">
						{% for Photo in Produit.photos %}
							{% if "jacket.jpg" == Photo.Nom %}
								<a href="{{path("app_Produit",{'id':Produit.id})}}">
									<img class="card-img-top" style="width: 16rem;" src="{{Photo.chemin}}" alt="Photo du produit">
									<a>
									{% endif %}
								{% endfor %}
								<div class="card-body">
									<h5 class="card-title">{{ Produit.nom }}</h5>
									{% for Supporter in Produit.supporters  %}
										<span class="badge rounded-pill text-bg-dark">{{ Supporter.support.nom }}</span>
									{% endfor %}
									{% if is_granted('IS_AUTHENTICATED_FULLY') %}
										{% if Produit in app.user.aimer %}
											<a href="{{path("app_adorer",{'id':Produit.id})}}">
												<i class="bi bi-suit-heart-fill text-danger"></i>
											</a>
										{% else %}
											<a href="{{path("app_adorer",{'id':Produit.id})}}">
												<i class="bi bi-suit-heart text-danger"></i>
											</a>
										{% endif %}
									{% else %}
										<a href="{{path("app_adorer",{'id':Produit.id})}}">
											<i class="bi bi-suit-heart text-danger"></i>
										</a>
									{% endif %}
								
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			{% endfor %}
		{% endblock %}