src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $rue = null;

    #[ORM\Column(length: 5)]
    private ?string $codePostal = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    private ?string $pays = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 10)]
    private ?string $numero = null;

    #[ORM\Column(length: 10)]
    private ?string $telephone = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $dateInscription = null;

    #[ORM\ManyToMany(targetEntity: Produit::class, inversedBy: 'users')]
    private Collection $aimer;

    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Panier $Panier = null;

    public function __construct()
    {
        $this->aimer = new ArrayCollection();
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(string $rue): static
    {
        $this->rue = $rue;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): static
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): static
    {
        $this->numero = $numero;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeImmutable
    {
        return $this->dateInscription;
    }

    public function setDateInscription(\DateTimeImmutable $dateInscription): static
    {
        $this->dateInscription = $dateInscription;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getAimer(): Collection
    {
        return $this->aimer;
    }

    public function addAimer(Produit $aimer): static
    {

        
        if (!$this->aimer->contains($aimer)) {
            $this->aimer->add($aimer);
        }


        return $this;
    }

    public function removeAimer(Produit $aimer): static
    {
        $this->aimer->removeElement($aimer);

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->Panier;
    }

    public function setPanier(?Panier $Panier): static
    {
        $this->Panier = $Panier;

        return $this;
    }

    

    
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Repository\UserRepository;
use App\Entity\User;
use App\Form\RoleType;
use App\Form\UserType;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
    
    #[Route('/Profil', name: 'app_profil')]
    public function Profil(UserRepository $UserRepository): Response
    { 
        return $this->render('security/compte.html.twig', [
            
        ]);
    }

    #[Route('/private-modifier_profil/{id}', name: 'app_modifier_User')]
    public function modifierProfil(Request $request,User $User,EntityManagerInterface $em): Response
    {   
        $form = $this->createForm(UserType::class, $user);
        if($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted()&&$form->isValid()){
                $em->persist($user);
                $em->flush();
                $this->addFlash('notice','Role modifiée');   
                return $this->redirectToRoute('app_user');
        } 
        return $this->render('security/user.html.twig', [
            'form' => $form->createView()
        ]);
        
        }
       
    }

    #[Route('/mod-liste_user', name: 'app_user')]
    public function liste_user(UserRepository $UserRepository): Response
    { 
        $Users = $UserRepository->findAll();
        return $this->render('base/liste-user.html.twig', [
            'Users' => $Users
        ]);
    }
    
    #[Route('/mod-modifier-role/{id}', name: 'app_modifierRoles')]
    public function modifierRole(Request $request, User $user,EntityManagerInterface $em): Response
    {
        $form = $this->createForm(ModifierProduitType::class, $user);
        if($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted()&&$form->isValid()){
            $em->persist($user);
            $em->flush();
            $this->addFlash('notice','Produit modifiée');
            return $this->redirectToRoute('app_listeProduit');
            }
        }
        return $this->render('base/modifier-Roles.html.twig', [
            'form' => $form->createView()
        ]);
    }
    


    #[Route('/private-listeSupporter', name: 'app_listeSupporter')]
    public function listeSupporter(SupporterRepository $SupporterRepository): Response
    {
        $Supporters = $SupporterRepository->findAll();
       return $this->render('produit/liste-Supporter.html.twig', [
          'Supporters' => $Supporters
       ]);
    }
}

templates/security/compte.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}-Profil
{% endblock %}
{% block body %}
	<h1 class="text-center text-primary mt-4 pt-4 display-1 fw-bold" style="font-family:Helvetica, sans-serif; text-align:center;">Profil</h1>
	<div class="row justify-content-center">
	<tr class="fw-bold text-primary ">
		<th scope="col">Email:
		</th>
		<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.email}}</td>

	</tr>
	</br>
	<tr class="fw-bold text-primary ">
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">Prénom:</th>
		<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.prenom}}</td>
	</tr>
	</br>
	<tr class="fw-bold text-primary ">
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">Nom:</th>
		<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.nom}}</td>
	</tr>
	</br>
	<tr class="fw-bold text-primary ">
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">Telephone:</th>
		<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.telephone}}</td>
	</tr>
	</br>
	<tr>
		<th scope="col" style="Helvetica, sans-serif; text-align:center;">numéro:</th>
		<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.numero}}</td>
	</tr>
	</br>
	<tr>
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">rue:</th>
		<td style"font-family:Helvetica, sans-serif; text-align:center;">{{app.user.rue}}</td>
	</tr>
	</br>
	<tr>
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">ville:</th>
		<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.ville}}</td>
	</tr>
	</br>
	<tr>
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">Code Postal:</th>
		<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.codePostal}}</td>
	</tr>
	</br>
	<tr>
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">Pays:</th>
	<td style="font-family:Helvetica, sans-serif; text-align:center;">{{app.user.Pays}}</td>
	</tr>
	</br>
	<tr>
		<th scope="col" style="font-family:Helvetica, sans-serif; text-align:center;">Role:</th>
		{% if "ROLE_ADMIN" in app.user.roles  %}
			<td style="Helvetica, sans-serif; text-align:center;">Adminitrateur</td>
		{% elseif "ROLE_MOD" in app.user.roles %}
			<td style="Helvetica, sans-serif; text-align:center;">Moderation</td>
		{% else %}
			<td style="Helvetica, sans-serif; text-align:center;">Utilisateur</td>
		{% endif %}
	</tr>
	</br>
	<td><a href="{{path("app_modifier_User",{'id':app.user.id})}}"><i class="bi bi-pen-fill text-dark"></i></a></td>
	</div>
	{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}Connectez-vous{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1 class="text-center text-primary mt-4 pt-4 display-1 fw-bold">connectez-vous</h1>
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 bg-white p-4 m-0 text-primary">
            <form method="post">
                {% if error %}
                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}

                {% if app.user %}
                    <div class="mb-3">You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a></div>
                {% endif %}
    
                <label for="inputEmail">Email</label>
                <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
                <label for="inputPassword">Mot de passe</label>
                <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

                <input type="hidden" name="_csrf_token"value="{{ csrf_token('authenticate') }}">

                <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" name="_remember_me"> souvenir de moi
                </label>
            </div>
            <div class="text-center">
            <button class="btn btn-lg btn-success mt-2" type="submit">
                se connecter
            </button>
        </div>
    </form>
    </div>
</div>
</div>
{% endblock %}

templates/security/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}- modifier votre Profit{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-10 text-primary">
            {{form(form)}}
        </div>
    </div>
</div>

{% endblock %}